### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by andress134** [Mrakovic-ORG/CFUnmitigate#1]
Your script is patched, using cloudscraper can't bypass new challenge.
Cloudscraper is ouptdated
Do u have alternative for uam?
@MrakDev

**Comment by 0x11DFE** [comment]
There is no npm module i am aware of that support new cloudflare uam, if you know any please let me know.

**Comment by andress134** [comment]
> There is no npm module i am aware of that support new cloudflare uam, if you know any please let me know.

what about this, sir ? 
https://github.com/JimmyLaurent/cloudflare-scraper
https://github.com/ngosang/FlareSolverr

**Comment by 0x11DFE** [comment]
Both are using [Puppeteer](https://www.npmjs.com/package/puppeteer) which is based on Chromium so i would not recommend using these for ddos.

**Comment by andress134** [comment]
> Both are using [Puppeteer](https://www.npmjs.com/package/puppeteer) which is based on Chromium so i would not recommend using these for ddos.

hmm yes, i think no any js lib can bypass new challenge
Found onother lib updated, but is java https://github.com/zhkrb/cloudflare-scrape-Android  so i think can't
What about captcha sir, your script  can be updated using 2captcha or anticaptcha lib to bypass hcaptcha, or also need any updated lib like cloudscraper?

**Comment by 0x11DFE** [comment]
I am not willing to promote any third party paid captcha solving services.

**Comment by andress134** [comment]
> I am not willing to promote any third party paid captcha solving services.

U can do it for me, for $ ?
we need a script to bypass cloudflare hcaptcha
I got one old based privacypass but require updated, after cloudflare updated script stoped working

**Comment by 0x11DFE** [comment]
Out of context, If you have another issue with this script please let me know other close this issue.

**Comment by andress134** [comment]
> Out of context, If you have another issue with this script please let me know other close this issue.

hey sir, this lib can bypass iuam and hcaptcha https://github.com/Wyvern-Balls/Cloudflare-Bypass-Script the solver is in js, i think some guy use it for bypassing
