### ISSUE TITLE
About Update

### ISSUE THREAD

**Issue by Cosmysd** [Mrakovic-ORG/CFUnmitigate#2]
Hello admin, @0x11DFE do u will update this version for cf? i see u ask about any nodejs lib that can bypass new challenge,  here is some lib updated
https://github.com/yarsky-tgz/scraper-http-client-request
https://github.com/zedd3v/hsolve
https://github.com/pguardiario/captchas
I THINK this lib can bypass new challenge iuam + hcaptcha, can be used it for your script?
Thank

**Comment by 0x11DFE** [comment]
"hSolve" is pretty slow and i have no idea what to do once the hcaptcha key is fetched.
"Captchas" is using selenium and requires a paid api key from 2captcha.
"scraper-http-client-request" needs improvements on its documentation i cannot understand how the api works.

**Comment by Cosmysd** [comment]
> "hSolve" is pretty slow and i have no idea what to do once the hcaptcha key is fetched.
> "Captchas" is using selenium and requires a paid api key from 2captcha.
> "scraper-http-client-request" needs improvements on its documentation i cannot understand how the api works.

If i pay you can u do it,using some lib for bypass hcaptcha, using 3rd party like anticaptcha?
Or do u know golang? i know some lib for golang that can bypass iuam and hcaptcha, also got a script but is compiled an use license, do u know if the script can reverse and remove license? I'll pay for help

**Comment by 0x11DFE** [comment]
In here i can only support you for our open source projects, i will not be doing beside private work.
No i have no knowledge in golang.
